global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth_service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment_service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'board-service'
    static_configs:
      - targets: ['board_service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'calendar-service'
    static_configs:
      - targets: ['calendar_service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s