services:
  api-gateway:
    build:
      context: ../../services/api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ../../services/api_gateway/config:/root/config:ro
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  config-data: