services:
  api-gateway:
    build:
      context: ../../services/api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    environment:
      PORT: ${API_GATEWAY_PORT}
      BOARD_SERVICE_ADDR: ${BOARD_SERVICE_ADDR}
      PAYMENT_SERVICE_ADDR: ${PAYMENT_SERVICE_ADDR}
      CALENDAR_SERVICE_ADDR: ${CALENDAR_SERVICE_ADDR}
      AUTH_SERVICE_ADDR: ${AUTH_SERVICE_ADDR}
      OTEL_ADDR: ${OTEL_ADDR}
      APP_MODE: ${APP_MODE}
    volumes:
      - ../../services/api_gateway/config:/root/config:ro
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    external: true
    name: seiflow_backend

volumes:
  config-data: