# Board создает свои ресурсы
networks:
  board_net:
    driver: bridge
  backend:
    driver: bridge

volumes:
  board_mongo_data:
    driver: local
  board_redis_data:
    driver: local

services:
  board_service:
    build: ../../services/board_service
    container_name: board_service
    ports:
      - "${BOARD_SERVICE_PORT}:8000"
    networks:
      - board_net
      - backend
    depends_on:
      board_mongo:
        condition: service_healthy
      board_redis:
        condition: service_healthy
    environment:
      - MONGO_HOST=board_mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
      - REDIS_HOST=board_redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  board_mongo:
    image: mongo:4.4
    container_name: board_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - board_mongo_data:/data/db
    ports:
      - "${BOARD_MONGO_PORT}:27017"
    networks:
      - board_net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  board_redis:
    image: redis:latest
    container_name: board_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "${BOARD_REDIS_PORT}:6379"
    volumes:
      - board_redis_data:/data
    networks:
      - board_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $$REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $$REDIS_USER on >$$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true

  board_mongo_express:
    image: mongo-express:0.54
    container_name: board_mongo_express
    restart: unless-stopped
    ports:
      - "${BOARD_MONGO_EXPRESS_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@board_mongo:27017/
    networks:
      - board_net
    depends_on:
      board_mongo:
        condition: service_healthy