networks:
  board_net:
    driver: bridge
  backend:
    external: true
    name: seiflow_backend

volumes:
  board_redis_data:
    driver: local

services:
  board_service:
    build: 
      context: ../../services/board_service
      dockerfile: Dockerfile
    container_name: board_service
    ports:
      - "${BOARD_SERVICE_PORT}:8090"
    networks:
      - board_net
      - backend
    depends_on:
      board_redis:
        condition: service_healthy
    environment:
      REDIS_HOST: board_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${BOARD_REDIS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb+srv://${BOARD_MONGO_ROOT_USERNAME}:${BOARD_MONGO_ROOT_PASSWORD}@board.kkbc5wl.mongodb.net/?retryWrites=true&w=majority&appName=${BOARD_MONGO_DATABASE}
      KAFKA_BROKERS: "${KAFKA_BROKERS}"
      OTEL_ADDR: ${OTEL_ADDR}
      PORT: ${BOARD_SERVICE_PORT}
    restart: unless-stopped

  board_redis:
    image: redis:7.4-alpine
    container_name: board_redis
    restart: unless-stopped
    ports:
      - "${BOARD_REDIS_PORT}:6379"
    volumes:
      - board_redis_data:/data
    networks:
      - board_net
    command: redis-server --requirepass ${BOARD_REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${BOARD_REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5