# Board создает свои ресурсы
networks:
  board_net:
    driver: bridge
  backend:
    driver: bridge

volumes:
  board_redis_data:
    driver: local

services:
  board_service:
    build: ../../services/board_service
    container_name: board_service
    ports:
      - "${BOARD_SERVICE_PORT}:8000"
    networks:
      - board_net
      - backend
    depends_on:
      board_redis:
        condition: service_healthy
    environment:
      - MONGO_HOST=board_mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
      - REDIS_HOST=board_redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  board_redis:
    image: redis:latest
    container_name: board_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "${BOARD_REDIS_PORT}:6379"
    volumes:
      - board_redis_data:/data
    networks:
      - board_net
    command: >
      redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true