# Calendar создает свои ресурсы
networks:
  calendar_net:
    driver: bridge
  backend:
    driver: bridge

volumes:
  calendar_redis_data:
    driver: local

services:
  calendar_service:
    build: ../../services/calendar_service
    container_name: calendar_service
    ports:
      - "${CALENDAR_SERVICE_PORT}:8000"
    networks:
      - calendar_net
      - backend
    depends_on:
      calendar_redis:
        condition: service_healthy
    environment:
      - MONGO_HOST=calendar_mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
      - REDIS_HOST=calendar_redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  calendar_redis:
    image: redis:latest
    container_name: calendar_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "${CALENDAR_REDIS_PORT}:6379"
    volumes:
      - calendar_redis_data:/data
    networks:
      - calendar_net
    command: >
       redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true