# Calendar создает свои ресурсы
networks:
  calendar_net:
    driver: bridge
  backend:
    driver: bridge

volumes:
  calendar_mongo_data:
    driver: local
  calendar_redis_data:
    driver: local

services:
  calendar_service:
    build: ../../services/calendar_service
    container_name: calendar_service
    ports:
      - "${CALENDAR_SERVICE_PORT}:8000"
    networks:
      - calendar_net
      - backend
    depends_on:
      calendar_mongo:
        condition: service_healthy
      calendar_redis:
        condition: service_healthy
    environment:
      - MONGO_HOST=calendar_mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
      - REDIS_HOST=calendar_redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  calendar_mongo:
    image: mongo:4.4
    container_name: calendar_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - calendar_mongo_data:/data/db
    ports:
      - "${CALENDAR_MONGO_PORT}:27017"
    networks:
      - calendar_net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  calendar_redis:
    image: redis:latest
    container_name: calendar_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "${CALENDAR_REDIS_PORT}:6379"
    volumes:
      - calendar_redis_data:/data
    networks:
      - calendar_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
       redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true

  calendar_mongo_express:
    image: mongo-express:0.54
    container_name: calendar_mongo_express
    restart: unless-stopped
    ports:
      - "${CALENDAR_MONGO_EXPRESS_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - calendar_net
    depends_on:
      calendar_mongo:
        condition: service_healthy