networks:
  calendar_net:
    driver: bridge
  backend:
    external: true
    name: seiflow_backend

volumes:
  calendar_mongo_data:
    driver: local
  calendar_redis_data:
    driver: local

services:
  calendar_service:
    build: 
      context: ../../services/calendar_service
      dockerfile: Dockerfile
    container_name: calendar_service
    ports:
      - "${CALENDAR_SERVICE_PORT}:8092"
    networks:
      - calendar_net
      - backend
    depends_on:
      calendar_mongo:
        condition: service_healthy
      calendar_redis:
        condition: service_healthy
    environment:
      MONGO_HOST: calendar_mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: ${CALENDAR_MONGO_ROOT_USERNAME}
      MONGO_PASSWORD: ${CALENDAR_MONGO_ROOT_PASSWORD}
      MONGO_DATABASE: ${CALENDAR_MONGO_DATABASE}
      REDIS_HOST: calendar_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${CALENDAR_REDIS_PASSWORD}
    restart: unless-stopped

  calendar_mongo:
    image: mongo:7
    container_name: calendar_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CALENDAR_MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CALENDAR_MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${CALENDAR_MONGO_DATABASE}
    volumes:
      - calendar_mongo_data:/data/db
    ports:
      - "${CALENDAR_MONGO_PORT}:27017"
    networks:
      - calendar_net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  calendar_redis:
    image: redis:7-alpine
    container_name: calendar_redis
    restart: unless-stopped
    ports:
      - "${CALENDAR_REDIS_PORT}:6379"
    volumes:
      - calendar_redis_data:/data
    networks:
      - calendar_net
    command: redis-server --requirepass ${CALENDAR_REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${CALENDAR_REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  calendar_mongo_express:
    image: mongo-express
    container_name: calendar_mongo_express
    restart: unless-stopped
    ports:
      - "${CALENDAR_MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${CALENDAR_MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${CALENDAR_MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: calendar_mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      calendar_mongo:
        condition: service_healthy
    networks: 
      - calendar_net