networks:
  calendar_net:
    driver: bridge
  backend:
    external: true
    name: seiflow_backend

volumes:
  calendar_redis_data:
    driver: local

services:
  calendar_service:
    build: 
      context: ../../services/calendar_service
      dockerfile: Dockerfile
    container_name: calendar_service
    ports:
      - "${CALENDAR_SERVICE_PORT}:8092"
    networks:
      - calendar_net
      - backend
    depends_on:
      calendar_redis:
        condition: service_healthy
    environment:
      MONGO_HOST: calendar_mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: ${CALENDAR_MONGO_ROOT_USERNAME}
      MONGO_PASSWORD: ${CALENDAR_MONGO_ROOT_PASSWORD}
      MONGO_DATABASE: ${CALENDAR_MONGO_DATABASE}
      REDIS_HOST: calendar_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${CALENDAR_REDIS_PASSWORD}
    restart: unless-stopped

  calendar_redis:
    image: redis:7.4-alpine
    container_name: calendar_redis
    restart: unless-stopped
    ports:
      - "${CALENDAR_REDIS_PORT}:6379"
    volumes:
      - calendar_redis_data:/data
    networks:
      - calendar_net
    command: redis-server --requirepass ${CALENDAR_REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${CALENDAR_REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5