version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./services/seiflow_frontend:/usr/share/nginx/html
    restart: unless-stopped
    