version: '3.9'

services:
  # ======== AUTH SERVICE ========
  auth_service:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - GO_ENV=development
      - GIN_MODE=debug
      - LOG_LEVEL=debug
    volumes:
      - ./services/auth_service:/go/src/app
    command: air -c .air.toml
    ports:
      - "${AUTH_SERVICE_PORT:-8000}:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  auth_postgres:
    ports:
      - "${AUTH_POSTGRES_PORT:-5431}:5432"
    volumes:
      - ./data/auth_service/postgres:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  auth_redis:
    ports:
      - "${AUTH_REDIS_PORT:-6381}:6379"
    volumes:
      - ./data/auth_service/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # ======== PAYMENT SERVICE ========
  payment_service:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - GO_ENV=development
      - GIN_MODE=debug
      - LOG_LEVEL=debug
    volumes:
      - ./services/payment_service:/go/src/app
    command: air -c .air.toml
    ports:
      - "${PAYMENT_SERVICE_PORT:-8001}:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  payment_postgres:
    ports:
      - "${PAYMENT_POSTGRES_PORT:-5430}:5432"
    volumes:
      - ./data/payment_service/postgres:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  payment_redis:
    ports:
      - "${PAYMENT_REDIS_PORT:-6380}:6379"
    volumes:
      - ./data/payment_service/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # ======== BOARD SERVICE ========
  board_service:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - GO_ENV=development
      - GIN_MODE=debug
      - LOG_LEVEL=debug
    volumes:
      - ./services/board_service:/go/src/app
    command: air -c .air.toml
    ports:
      - "${BOARD_SERVICE_PORT:-8002}:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  board_mongo:
    ports:
      - "${BOARD_MONGO_PORT:-27018}:27017"
    volumes:
      - ./data/board_service/mongo:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  board_mongo_express:
    ports:
      - "${BOARD_MONGO_EXPRESS_PORT:-8082}:8081"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  board_redis:
    ports:
      - "${BOARD_REDIS_PORT:-6382}:6379"
    volumes:
      - ./data/board_service/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # ======== CALENDAR SERVICE ========
  calendar_service:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - GO_ENV=development
      - GIN_MODE=debug
      - LOG_LEVEL=debug
    volumes:
      - ./services/calendar_service:/go/src/app
    command: air -c .air.toml
    ports:
      - "${CALENDAR_SERVICE_PORT:-8003}:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  calendar_mongo:
    ports:
      - "${CALENDAR_MONGO_PORT:-27017}:27017"
    volumes:
      - ./data/calendar_service/mongo:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  calendar_mongo_express:
    ports:
      - "${CALENDAR_MONGO_EXPRESS_PORT:-8081}:8081"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  calendar_redis:
    ports:
      - "${CALENDAR_REDIS_PORT:-6383}:6379"
    volumes:
      - ./data/calendar_service/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M